from dataclasses import dataclass, field

from app.schemas.analysis import IssueCategory


@dataclass(frozen=True)
class DiagnosticQuestion:
    id: str
    category: IssueCategory
    dimension: str
    question: str
    purpose: str
    related_causes: list[str]
    answer_type: str
    level1_safe: bool
    requires_admin_access: bool
    source_level: str
    source_refs: list[str]
    signals: list[str] = field(default_factory=list)
    avoid_if_signals: list[str] = field(default_factory=list)
    base_priority: int = 50


TAXONOMY_DOC = "docs/it-support-taxonomy.md"


DIAGNOSTIC_QUESTIONS: tuple[DiagnosticQuestion, ...] = (
    DiagnosticQuestion(
        id="general-affected-thing-action",
        category=IssueCategory.GENERAL_IT,
        dimension="exact_symptom",
        question="What exactly is not working, and what were you trying to do?",
        purpose="This routes the unknown issue to the safest visible support family before deeper checks.",
        related_causes=["insufficient_information", "wrong_support_family"],
        answer_type="text",
        level1_safe=True,
        requires_admin_access=False,
        source_level="C",
        source_refs=[f"{TAXONOMY_DOC}#general-unknown"],
        signals=["something", "stopped working", "not working", "weird"],
        base_priority=100,
    ),
    DiagnosticQuestion(
        id="general-error-behavior",
        category=IssueCategory.GENERAL_IT,
        dimension="error_message",
        question="What exact error message or warning do you see, or what unusual behavior happens?",
        purpose="Visible messages are safe evidence that can identify a support owner without system access.",
        related_causes=["visible_error", "unknown_owner"],
        answer_type="text",
        level1_safe=True,
        requires_admin_access=False,
        source_level="C",
        source_refs=[f"{TAXONOMY_DOC}#general-unknown"],
        signals=["error", "warning", "message", "unusual"],
        base_priority=90,
    ),
    DiagnosticQuestion(
        id="general-scope",
        category=IssueCategory.GENERAL_IT,
        dimension="scope",
        question="Is this affecting only you or other users/devices as well?",
        purpose="Scope separates a local issue from wider service or infrastructure impact.",
        related_causes=["single_user_issue", "wider_service_impact"],
        answer_type="scope",
        level1_safe=True,
        requires_admin_access=False,
        source_level="C",
        source_refs=[f"{TAXONOMY_DOC}#general-unknown"],
        signals=["only me", "everyone", "users", "devices"],
        base_priority=80,
    ),
    DiagnosticQuestion(
        id="general-business-impact",
        category=IssueCategory.GENERAL_IT,
        dimension="business_impact",
        question="Is this blocking work right now?",
        purpose="Business impact helps decide urgency and whether a support review is needed sooner.",
        related_causes=["work_blocked", "priority_needs_confirmation"],
        answer_type="yes_no_unknown",
        level1_safe=True,
        requires_admin_access=False,
        source_level="C",
        source_refs=[f"{TAXONOMY_DOC}#general-unknown"],
        signals=["blocked", "blocking", "urgent", "cannot work"],
        base_priority=75,
    ),
    DiagnosticQuestion(
        id="general-start-time",
        category=IssueCategory.GENERAL_IT,
        dimension="timing",
        question="Did it work before, and when did the problem start?",
        purpose="Timing helps connect the symptom to recent changes or recurring behavior.",
        related_causes=["recent_change", "intermittent_issue"],
        answer_type="text",
        level1_safe=True,
        requires_admin_access=False,
        source_level="C",
        source_refs=[f"{TAXONOMY_DOC}#general-unknown"],
        signals=["when", "started", "today", "yesterday"],
        base_priority=70,
    ),
    DiagnosticQuestion(
        id="general-recent-change",
        category=IssueCategory.GENERAL_IT,
        dimension="recent_change",
        question="Did anything change recently, such as device setup, password, network, software, or location?",
        purpose="Recent changes often explain the safest next diagnostic path.",
        related_causes=["recent_change", "configuration_change"],
        answer_type="text",
        level1_safe=True,
        requires_admin_access=False,
        source_level="C",
        source_refs=[f"{TAXONOMY_DOC}#general-unknown"],
        signals=["changed", "recently", "new", "update"],
        base_priority=60,
    ),
    DiagnosticQuestion(
        id="login-target",
        category=IssueCategory.LOGIN_ACCOUNT,
        dimension="affected_account_or_app",
        question="Which account, app, or service are you trying to log in to?",
        purpose="The affected account or service separates identity issues from app-specific access issues.",
        related_causes=["wrong_account_path", "app_specific_login_issue"],
        answer_type="text",
        level1_safe=True,
        requires_admin_access=False,
        source_level="C",
        source_refs=[f"{TAXONOMY_DOC}#account--login--mfa"],
        signals=["login", "log in", "sign in", "account"],
        base_priority=100,
    ),
    DiagnosticQuestion(
        id="login-error",
        category=IssueCategory.LOGIN_ACCOUNT,
        dimension="error_message",
        question="What exact error message do you see?",
        purpose="Exact wording separates password, lockout, MFA, permission, and app-specific symptoms.",
        related_causes=["incorrect_password", "account_locked", "permission_boundary"],
        answer_type="text",
        level1_safe=True,
        requires_admin_access=False,
        source_level="C",
        source_refs=[f"{TAXONOMY_DOC}#account--login--mfa"],
        signals=["error", "message", "locked", "incorrect"],
        base_priority=90,
    ),
    DiagnosticQuestion(
        id="login-mfa",
        category=IssueCategory.LOGIN_ACCOUNT,
        dimension="mfa_behavior",
        question="Are you being asked for MFA, and can you complete the MFA prompt?",
        purpose="MFA behavior separates credential problems from approval or authenticator issues.",
        related_causes=["mfa_prompt_failure", "authenticator_issue"],
        answer_type="yes_no_unknown",
        level1_safe=True,
        requires_admin_access=False,
        source_level="C",
        source_refs=[f"{TAXONOMY_DOC}#account--login--mfa"],
        signals=["mfa", "authenticator", "code", "approve"],
        base_priority=80,
    ),
    DiagnosticQuestion(
        id="login-password-change",
        category=IssueCategory.LOGIN_ACCOUNT,
        dimension="recent_change",
        question="Did you recently change your password or receive any password expiry message?",
        purpose="Recent password changes often explain saved credential or expiry-related failures.",
        related_causes=["saved_credential_issue", "expired_password"],
        answer_type="yes_no_unknown",
        level1_safe=True,
        requires_admin_access=False,
        source_level="C",
        source_refs=[f"{TAXONOMY_DOC}#account--login--mfa"],
        signals=["password", "expired", "changed"],
        base_priority=70,
    ),
    DiagnosticQuestion(
        id="login-scope",
        category=IssueCategory.LOGIN_ACCOUNT,
        dimension="scope",
        question="Is this affecting only you or other users as well?",
        purpose="Scope separates a single account path from wider identity or service impact.",
        related_causes=["single_account_issue", "identity_service_impact"],
        answer_type="scope",
        level1_safe=True,
        requires_admin_access=False,
        source_level="C",
        source_refs=[f"{TAXONOMY_DOC}#account--login--mfa"],
        signals=["only me", "users", "everyone"],
        base_priority=60,
    ),
    DiagnosticQuestion(
        id="vpn-error",
        category=IssueCategory.VPN_REMOTE_ACCESS,
        dimension="error_message",
        question="What exact VPN error message do you see?",
        purpose="Exact VPN wording separates authentication, MFA, client, profile, and connectivity symptoms.",
        related_causes=["vpn_authentication_issue", "vpn_client_issue", "vpn_profile_issue"],
        answer_type="text",
        level1_safe=True,
        requires_admin_access=False,
        source_level="C",
        source_refs=[f"{TAXONOMY_DOC}#network--vpn--wi-fi"],
        signals=["vpn", "error", "cannot connect"],
        base_priority=100,
    ),
    DiagnosticQuestion(
        id="vpn-internet",
        category=IssueCategory.VPN_REMOTE_ACCESS,
        dimension="internet_without_vpn",
        question="Can you access normal websites or the internet without the VPN connected?",
        purpose="This separates general internet connectivity from VPN-specific failure.",
        related_causes=["local_internet_issue", "vpn_specific_issue"],
        answer_type="yes_no_unknown",
        level1_safe=True,
        requires_admin_access=False,
        source_level="C",
        source_refs=[f"{TAXONOMY_DOC}#network--vpn--wi-fi"],
        signals=["internet", "website", "without vpn"],
        base_priority=90,
    ),
    DiagnosticQuestion(
        id="vpn-network-type",
        category=IssueCategory.VPN_REMOTE_ACCESS,
        dimension="network_type",
        question="Are you connecting from home Wi-Fi, mobile hotspot, public Wi-Fi, or office network?",
        purpose="Network type helps separate local network restrictions from VPN client or account behavior.",
        related_causes=["network_restriction", "vpn_client_issue"],
        answer_type="choice",
        level1_safe=True,
        requires_admin_access=False,
        source_level="C",
        source_refs=[f"{TAXONOMY_DOC}#network--vpn--wi-fi"],
        signals=["home", "wifi", "wi-fi", "hotspot", "public", "office"],
        base_priority=80,
    ),
    DiagnosticQuestion(
        id="vpn-mfa-password",
        category=IssueCategory.VPN_REMOTE_ACCESS,
        dimension="auth_behavior",
        question="Are you prompted for MFA or password when connecting to VPN?",
        purpose="Authentication behavior separates account/MFA symptoms from network or client symptoms.",
        related_causes=["vpn_authentication_issue", "mfa_prompt_failure"],
        answer_type="yes_no_unknown",
        level1_safe=True,
        requires_admin_access=False,
        source_level="C",
        source_refs=[f"{TAXONOMY_DOC}#network--vpn--wi-fi"],
        signals=["mfa", "password", "authentication"],
        base_priority=70,
    ),
    DiagnosticQuestion(
        id="printer-selected",
        category=IssueCategory.PRINTER,
        dimension="selected_device",
        question="Are you selecting the correct printer when sending the job?",
        purpose="The selected printer separates wrong queue or stale printer objects from device or service issues.",
        related_causes=["wrong_selected_printer", "stale_printer_object"],
        answer_type="yes_no_unknown",
        level1_safe=True,
        requires_admin_access=False,
        source_level="C",
        source_refs=[f"{TAXONOMY_DOC}#printer--scanner"],
        signals=["printer", "print", "queue"],
        base_priority=100,
    ),
    DiagnosticQuestion(
        id="printer-queue",
        category=IssueCategory.PRINTER,
        dimension="queue_state",
        question="Does the print job appear in the print queue, or does it disappear immediately?",
        purpose="Queue behavior separates local queue issues from printer/device or shared print path issues.",
        related_causes=["stuck_local_queue", "wrong_selected_printer", "shared_print_issue"],
        answer_type="text",
        level1_safe=True,
        requires_admin_access=False,
        source_level="C",
        source_refs=[f"{TAXONOMY_DOC}#printer--scanner"],
        signals=["nothing prints", "print job", "queue", "document"],
        base_priority=90,
    ),
    DiagnosticQuestion(
        id="printer-online",
        category=IssueCategory.PRINTER,
        dimension="visible_device_status",
        question="Is the printer online and showing Ready, or is there a visible paper, toner, jam, or error message?",
        purpose="Visible printer state separates simple device status from queue or client-side symptoms.",
        related_causes=["printer_offline", "paper_toner_jam", "visible_printer_error"],
        answer_type="text",
        level1_safe=True,
        requires_admin_access=False,
        source_level="C",
        source_refs=[f"{TAXONOMY_DOC}#printer--scanner"],
        signals=["offline", "paper", "toner", "jam", "error"],
        avoid_if_signals=["printer is online", "printer online", "online"],
        base_priority=80,
    ),
    DiagnosticQuestion(
        id="printer-other-users",
        category=IssueCategory.PRINTER,
        dimension="scope",
        question="Are other users able to print to the same printer?",
        purpose="Scope separates one-user client issues from shared printer or print service impact.",
        related_causes=["single_user_print_issue", "shared_print_issue"],
        answer_type="yes_no_unknown",
        level1_safe=True,
        requires_admin_access=False,
        source_level="C",
        source_refs=[f"{TAXONOMY_DOC}#printer--scanner"],
        signals=["other users", "same printer"],
        base_priority=70,
    ),
    DiagnosticQuestion(
        id="printer-document-scope",
        category=IssueCategory.PRINTER,
        dimension="app_document_scope",
        question="Does the issue happen from one document/app only, or from every document/app?",
        purpose="Document or app scope separates file/app-specific print failures from the wider print path.",
        related_causes=["document_specific_issue", "application_print_issue", "printer_path_issue"],
        answer_type="choice",
        level1_safe=True,
        requires_admin_access=False,
        source_level="C",
        source_refs=[f"{TAXONOMY_DOC}#printer--scanner"],
        signals=["document", "app", "every"],
        base_priority=60,
    ),
    DiagnosticQuestion(
        id="file-path",
        category=IssueCategory.FILE_ACCESS_PERMISSION,
        dimension="path_or_link",
        question="What is the folder path, link, or shared drive name you are trying to access?",
        purpose="The exact path separates wrong link/path issues from permission or platform boundaries.",
        related_causes=["wrong_path", "missing_permission", "platform_boundary"],
        answer_type="text",
        level1_safe=True,
        requires_admin_access=False,
        source_level="C",
        source_refs=[f"{TAXONOMY_DOC}#file--permission"],
        signals=["shared folder", "network drive", "link", "path"],
        base_priority=100,
    ),
    DiagnosticQuestion(
        id="file-error",
        category=IssueCategory.FILE_ACCESS_PERMISSION,
        dimension="error_message",
        question="What exact permission or access error do you see?",
        purpose="Exact wording separates access denied, path missing, sync, and request-access symptoms.",
        related_causes=["missing_permission", "path_not_found", "sync_issue"],
        answer_type="text",
        level1_safe=True,
        requires_admin_access=False,
        source_level="C",
        source_refs=[f"{TAXONOMY_DOC}#file--permission"],
        signals=["permission", "access denied", "error", "cannot access"],
        base_priority=90,
    ),
    DiagnosticQuestion(
        id="file-previous-access",
        category=IssueCategory.FILE_ACCESS_PERMISSION,
        dimension="previous_access",
        question="Were you able to access this folder before?",
        purpose="Previous access separates a new permission request from a changed or broken access path.",
        related_causes=["permission_changed", "new_access_request"],
        answer_type="yes_no_unknown",
        level1_safe=True,
        requires_admin_access=False,
        source_level="C",
        source_refs=[f"{TAXONOMY_DOC}#file--permission"],
        signals=["before", "previously", "used to"],
        base_priority=80,
    ),
    DiagnosticQuestion(
        id="file-other-users",
        category=IssueCategory.FILE_ACCESS_PERMISSION,
        dimension="scope",
        question="Can other users who should have access open the same folder?",
        purpose="Scope separates a single-user permission path from wider storage or platform impact.",
        related_causes=["single_user_permission_issue", "shared_storage_issue"],
        answer_type="yes_no_unknown",
        level1_safe=True,
        requires_admin_access=False,
        source_level="C",
        source_refs=[f"{TAXONOMY_DOC}#file--permission"],
        signals=["other users", "same folder"],
        base_priority=70,
    ),
    DiagnosticQuestion(
        id="display-power",
        category=IssueCategory.DISPLAY_MONITOR,
        dimension="monitor_power",
        question="Is there any power light on the monitor, or does it look completely off?",
        purpose="Monitor power state separates display power from cable, input, dock, or computer state.",
        related_causes=["monitor_power_issue", "sleep_state", "display_path_issue"],
        answer_type="text",
        level1_safe=True,
        requires_admin_access=False,
        source_level="C",
        source_refs=[f"{TAXONOMY_DOC}#display--monitor--dock"],
        signals=["monitor", "off", "power", "light", "black"],
        base_priority=100,
    ),
    DiagnosticQuestion(
        id="display-computer-running",
        category=IssueCategory.DISPLAY_MONITOR,
        dimension="computer_state",
        question="Does the computer or laptop still appear to be running when the monitor is off?",
        purpose="Computer state separates a monitor/display path issue from a sleeping or powered-off computer.",
        related_causes=["computer_sleep_state", "monitor_path_issue"],
        answer_type="yes_no_unknown",
        level1_safe=True,
        requires_admin_access=False,
        source_level="C",
        source_refs=[f"{TAXONOMY_DOC}#display--monitor--dock"],
        signals=["computer", "laptop", "running", "sleep"],
        base_priority=90,
    ),
    DiagnosticQuestion(
        id="display-wake",
        category=IssueCategory.DISPLAY_MONITOR,
        dimension="wake_behavior",
        question="Can the monitor wake up after moving the mouse, pressing a key, or pressing the monitor power button?",
        purpose="Wake behavior separates sleep/power state from cable, dock, or display detection issues.",
        related_causes=["sleep_state", "input_wake_issue", "display_detection_issue"],
        answer_type="yes_no_unknown",
        level1_safe=True,
        requires_admin_access=False,
        source_level="C",
        source_refs=[f"{TAXONOMY_DOC}#display--monitor--dock"],
        signals=["wake", "mouse", "keyboard", "key", "sleep"],
        base_priority=80,
    ),
    DiagnosticQuestion(
        id="display-connection-path",
        category=IssueCategory.DISPLAY_MONITOR,
        dimension="display_path",
        question="Is the monitor connected directly to the computer, or through a dock, adapter, or docking station?",
        purpose="Connection path separates monitor/cable checks from dock, adapter, or port-specific symptoms.",
        related_causes=["dock_issue", "adapter_issue", "cable_or_port_issue"],
        answer_type="choice",
        level1_safe=True,
        requires_admin_access=False,
        source_level="C",
        source_refs=[f"{TAXONOMY_DOC}#display--monitor--dock"],
        signals=["dock", "adapter", "cable", "hdmi", "usb-c", "displayport"],
        base_priority=70,
    ),
)


def questions_for_category(category: IssueCategory) -> list[DiagnosticQuestion]:
    return [
        question
        for question in DIAGNOSTIC_QUESTIONS
        if question.category == category
    ]
